# Generated by Django 3.2.5 on 2022-12-11 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20221208_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=3500, null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='')),
                ('variant', models.CharField(max_length=200, null=True)),
                ('first_registration', models.IntegerField(null=True)),
                ('engine_capacity', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('mileage', models.IntegerField(null=True)),
                ('seller', models.CharField(choices=[('All', 'All'), ('Dealer', 'Dealer'), ('Private', 'Private')], max_length=200, null=True)),
                ('first_owner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('broken', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('no_crashed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=200, null=True)),
                ('manual_auto', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('num_of_doors', models.IntegerField(null=True)),
                ('color_type', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carapp.brand')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carapp.fuel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carapp.profile')),
            ],
        ),
    ]
