# Generated by Django 3.2.5 on 2022-12-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_advert_brand_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_intro',
            new_name='phone_number',
        ),
    ]
