# Generated by Django 3.2.5 on 2022-12-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_rename_short_intro_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='broken',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='first_owner',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='manual_auto',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='seller',
        ),
    ]
