# Generated by Django 3.2.5 on 2023-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_auto_20230106_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='featured_image',
            field=models.ImageField(blank=True, default='profiles/user.png', null=True, upload_to='adverts/'),
        ),
    ]
