# Generated by Django 3.2.5 on 2023-01-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0007_alter_advert_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='featured_image',
            field=models.FileField(blank=True, default='profiles/user.png', null=True, upload_to='images/adverts/'),
        ),
    ]
