# Generated by Django 3.2.5 on 2023-01-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0008_alter_advert_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/adverts/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/user.png', null=True, upload_to='images/profiles/'),
        ),
    ]
