# Generated by Django 3.2.5 on 2023-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0010_alter_advert_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/user.png', null=True, upload_to='profiles/'),
        ),
    ]
