# Generated by Django 3.2.5 on 2023-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='adverts/'),
        ),
    ]
