# Generated by Django 3.2.5 on 2023-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='no_crashed',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='seller',
            field=models.CharField(choices=[('Dealer', 'Dealer'), ('Osoba Prywatna', 'Osoba Prywatna')], max_length=200, null=True),
        ),
    ]
