# Generated by Django 3.2.5 on 2023-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0016_auto_20230108_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
