# Generated by Django 3.2.5 on 2023-02-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0017_profile_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=200)),
                ('advert_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carapp.advert')),
            ],
        ),
    ]
