# Generated by Django 3.2.5 on 2023-02-22 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0019_auto_20230222_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereminder',
            name='advert_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
