# Generated by Django 3.2.5 on 2023-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0020_pricereminder_advert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereminder',
            name='advert_id',
            field=models.CharField(max_length=30),
        ),
    ]
