# Generated by Django 3.2.5 on 2023-02-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0021_alter_pricereminder_advert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereminder',
            name='advert_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carapp.advert'),
        ),
    ]
