# Generated by Django 3.2.5 on 2023-02-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0022_alter_pricereminder_advert_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricereminder',
            old_name='advert_id',
            new_name='advert',
        ),
    ]
