# Generated by Django 3.2.5 on 2023-02-22 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0024_rename_advert_pricereminder_advert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereminder',
            name='advert_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
