# Generated by Django 3.2.5 on 2023-02-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0026_auto_20230222_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereminder',
            name='advert_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carapp.advert'),
        ),
    ]
