# Generated by Django 3.2.5 on 2023-02-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0028_alter_pricereminder_advert_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceReminder',
        ),
    ]
