# Generated by Django 3.2.5 on 2023-02-23 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0030_pricereminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricereminder',
            name='id',
        ),
        migrations.AlterField(
            model_name='pricereminder',
            name='advert_id_owner',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
