# Generated by Django 3.2.5 on 2023-02-23 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0033_rename_advert_id_owner_pricereminderconnection_id_of_advert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricereminderconnection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pricereminderconnection',
            name='id_of_advert',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
