# Generated by Django 3.2.5 on 2023-02-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0034_auto_20230223_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricereminderconnection',
            name='id_of_advert',
            field=models.CharField(max_length=50),
        ),
    ]
