# Generated by Django 3.2.5 on 2023-03-01 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0035_alter_pricereminderconnection_id_of_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='engine_capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='advert',
            name='first_registration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='mileage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(500000), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='advert',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='power',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
