# Generated by Django 3.2.5 on 2023-03-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0036_auto_20230301_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='first_registration',
            field=models.IntegerField(null=True),
        ),
    ]
