# Generated by Django 3.2.5 on 2023-03-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0037_alter_advert_first_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='first_registration',
            field=models.DateField(null=True),
        ),
    ]
